CXX = g++
CXXFLAGS = -Wall -g -std=c++11 -O2 -D ET_TEST #-D DUMP_FREELIST
#FLAGS=-D ET_TEST
#DUMP=-D DUMP_FREELIST

PROGRAMS=sum02_double sum04_double sum06_double sum08_double sum02_ad sum04_ad sum06_ad sum08_ad sum02_hand sum04_hand sum06_hand sum08_hand

all: $(PROGRAMS)

clean:
	rm -f *.o $(PROGRAMS) *~

